# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-20 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='chairtype',
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='parttype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
