# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180720_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='price',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
