# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0003_parttype_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttype',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
