# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0010_auto_20180731_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parttype',
            name='price',
        ),
        migrations.AddField(
            model_name='parttype',
            name='cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
