# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-02 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chair', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chair.Chair')),
                ('chair_type', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='chair.ChairType')),
                ('part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.PartType')),
            ],
        ),
    ]
