# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-25 12:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180725_1235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderBuy',
            new_name='LeftItem',
        ),
        migrations.RenameField(
            model_name='leftitem',
            old_name='item',
            new_name='itemleft',
        ),
    ]
