# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-27 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0002_auto_20180720_0854'),
        ('parts', '0002_auto_20180720_1425'),
        ('order', '0003_auto_20180725_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_price', models.IntegerField()),
                ('chairtype_price', models.IntegerField()),
                ('part_price', models.IntegerField()),
                ('parttype_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chair.Chair')),
                ('chairtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chair.ChairType')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
                ('parttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PartType')),
            ],
        ),
        migrations.DeleteModel(
            name='LeftItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
