# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0002_auto_20180720_0854'),
        ('order', '0004_auto_20180727_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chair.Chair')),
            ],
        ),
        migrations.RemoveField(
            model_name='ordermanager',
            name='chair',
        ),
        migrations.RemoveField(
            model_name='ordermanager',
            name='chairtype',
        ),
        migrations.RemoveField(
            model_name='ordermanager',
            name='part',
        ),
        migrations.RemoveField(
            model_name='ordermanager',
            name='parttype',
        ),
        migrations.DeleteModel(
            name='OrderManager',
        ),
    ]
