# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180720_1425'),
        ('order', '0005_auto_20180730_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='parttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.PartType'),
        ),
    ]
