# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_parttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_of_item',
            field=models.IntegerField(default='', max_length=10),
        ),
    ]
