# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180731_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity_of_item',
            field=models.IntegerField(),
        ),
    ]
