# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20180731_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity_of_item',
        ),
    ]
