# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_remove_order_quantity_of_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_of_item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
