# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180720_1425'),
        ('chair', '0002_auto_20180720_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairtype',
            name='part_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parts.PartType'),
        ),
    ]
