# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0004_auto_20180730_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairtype',
            name='part_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.PartType'),
        ),
    ]
