# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0005_auto_20180730_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairtype',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
