# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chair', '0006_chairtype_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chairtype',
            name='parent_id',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
